[project]
name = "pyright-pytest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyright>=1.1.408",
    "pytest>=9.0.2",
]
